{% set version = '0.8.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tsibble
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tsibble_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tsibble/tsibble_{{ version }}.tar.gz
  sha256: a75053b0c4ff9b8c963cef19097379bc0f88ad864febc6fb3e50a280a85d76bf

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-anytime >=0.3.1
    - r-dplyr >=0.8.0
    - r-lubridate >=1.7.0
    - r-purrr >=0.2.3
    - r-rlang >=0.2.0
    - r-tibble >=2.0.1
    - r-tidyr
    - r-tidyselect
  run:
    - r-base
    - r-anytime >=0.3.1
    - r-dplyr >=0.8.0
    - r-lubridate >=1.7.0
    - r-purrr >=0.2.3
    - r-rlang >=0.2.0
    - r-tibble >=2.0.1
    - r-tidyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('tsibble')"           # [not win]
    - "\"%R%\" -e \"library('tsibble')\""  # [win]

about:
  home: https://tsibble.tidyverts.org
  license: GPL-3
  summary: Provides a 'tbl_ts' class (the 'tsibble') for temporal data in an  explicit data-
    and model-oriented format. The 'tsibble' provides tools to  easily manipulate and
    analyse temporal data, such as filling in time gaps, aggregating over calendar periods,
    performing rolling window calculations, and etc.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Type: Package
# Package: tsibble
# Title: Tidy Temporal Data Frames and Tools
# Version: 0.8.3
# Authors@R:  c(person(given = "Earo", family = "Wang", role = c("aut", "cre"), email = "earo.wang@gmail.com", comment = c(ORCID = "0000-0001-6448-5260")), person(given = "Di", family = "Cook", role = c("aut", "ths"), comment = c(ORCID = "0000-0002-3813-7155")), person(given = "Rob", family = "Hyndman", role = c("aut", "ths"), comment = c(ORCID = "0000-0002-2140-5352")), person(given = "Mitchell", family = "O'Hara-Wild", role = "aut", comment = c(ORCID = "0000-0001-6729-7695")))
# Description: Provides a 'tbl_ts' class (the 'tsibble') for temporal data in an  explicit data- and model-oriented format. The 'tsibble' provides tools to  easily manipulate and analyse temporal data, such as filling in time gaps, aggregating over calendar periods, performing rolling window calculations, and etc.
# License: GPL-3
# URL: https://tsibble.tidyverts.org
# BugReports: https://github.com/tidyverts/tsibble/issues
# Depends: R (>= 3.2.0)
# Imports: anytime (>= 0.3.1), dplyr (>= 0.8.0), lubridate (>= 1.7.0), purrr (>= 0.2.3), rlang (>= 0.2.0), tibble (>= 2.0.1), tidyr, tidyselect
# Suggests: covr, crayon, furrr, ggplot2 (>= 2.2.0), hms, knitr, nanotime, nycflights13 (>= 1.0.0), pillar (>= 1.0.1), rmarkdown, spelling, testthat, timeDate
# VignetteBuilder: knitr
# ByteCompile: true
# Encoding: UTF-8
# Language: en-GB
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-07-29 17:18:16 UTC; earo
# Author: Earo Wang [aut, cre] (<https://orcid.org/0000-0001-6448-5260>), Di Cook [aut, ths] (<https://orcid.org/0000-0002-3813-7155>), Rob Hyndman [aut, ths] (<https://orcid.org/0000-0002-2140-5352>), Mitchell O'Hara-Wild [aut] (<https://orcid.org/0000-0001-6729-7695>)
# Maintainer: Earo Wang <earo.wang@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-07-29 17:40:02 UTC
